### PR TITLE
Allow build on forks

### LINKED ISSUE #40: Forks cannot build with Github actions
With your updated CI setup, it is not possible to use the Github actions on forks due to the missing secrets.

I would propose to either split up `CI.yaml` into two files:
- CI.yaml - runs on all branches `*` (which then can be used by forks / pull requests as well)
- release.yaml (runs only on `main` and executes only the release steps)

Or minimum change: reorder steps, so the release steps will fail at the end.
That way contributors could still see the build output in Github action, example: https://github.com/kevinpapst/rymfony/actions/runs/379088085

I can work on a PR if you agree on one of the solutions.

### PR DESCRIPTION
**Pull request by kevinpapst**
Fixes #40 

Actually I only added `if: ${{ github.ref == 'refs/heads/main' }}` 3 times, but I thought I move the `Install SSH key` step after the build in the same time, so the dependency order is more obvious.

### CODE REVIEW

**Review by Pierstoval — APPROVED** [review]
Seems good to me, I'll merge it as-is and see if it works on the main branch :)

I had struggles with the `if` in the steps, it didn't seem to work, but we will sort it out eventually :)

**Comment by Pierstoval** [comment]
Thanks @kevinpapst!

**Comment by kevinpapst** [comment]
Well, it worked in my fork, so I hope it works here as well^^

**Comment by Pierstoval** [comment]
Perfect then! 👍

**Pull request merged**
