### PR TITLE
Add 'server' header on HTTP response

### PR DESCRIPTION
**Pull request by macintoshplus**
The result on cURL wit PHP-FPM.

```
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
< HTTP/2 200 
< x-some-random-header: some-random-value
< content-length: 976
< content-type: text/plain;charset=UTF-8
< server: Rymfony
< date: Thu, 03 Dec 2020 22:31:35 GMT
< 
Hey! It works!
```

### CODE REVIEW

**Comment by Pierstoval** [comment]
I'm not sure that it's necessary. Do you have any good arguments for this?

**Comment by macintoshplus** [comment]
In my computer, multiple webserver running in same time. I use this header to check if is the good server have send the response.

Sometimes, I user Symfony and Rymfony in same time for the same project. This header can distinguish between the two server.

**Comment by Pierstoval** [comment]
I think an opt-in flag should be used, like `--expose-server-header|-s` (other suggestions appreciated 😄).

If anyone wants to use this in production (which I don't recommend, but who knows what it's gonna be in the future?), the `Server` header shouldn't be exposed by default, hence an opt-in flag.

WDYT?

**Comment by macintoshplus** [comment]
Yes it's a good solution.

**Comment by macintoshplus** [comment]
The new result of `rymfony serve --help`

```
$ rymfony serve --help
rymfony-server:start 
Runs an HTTP server

USAGE:
    rymfony server:start [FLAGS] [OPTIONS]

FLAGS:
        --allow-http              Do not redirect HTTP request to HTTPS
    -d, --daemon                  Run the server in the background
    -s, --expose-server-header    Add server header into all response
    -h, --help                    Prints help information
        --no-tls                  Disable TLS
    -V, --version                 Prints version information

OPTIONS:
        --document-root <document-root>    Project's document root
        --passthru <passthru>              The PHP script all requests will be passed to
        --port <port>                      The TCP port to listen to [default: 8000]

```

**Comment by Pierstoval** [comment]
LGTM 👍 

Do you have any additionnal work to do here?

**Comment by macintoshplus** [comment]
No, this PR is ready to merge.

**Comment by Pierstoval** [comment]
Thanks @macintoshplus 🚀

**Pull request merged**
